CREATE TABLE IF NOT EXISTS "DeviceSessions" (
	"Id" SERIAL PRIMARY KEY,
	"DeviceId" TEXT NOT NULL,
	"Name" TEXT NOT NULL,
	"StartTime" TIMESTAMP NOT NULL,
	"EndTime" TIMESTAMP NOT NULL,
	"Version" TEXT NOT NULL
);