CREATE TABLE IF NOT EXISTS device_sessions (
	id SERIAL PRIMARY KEY,
	device_id TEXT NOT NULL,
	name TEXT NOT NULL,
	start_time TIMESTAMP NOT NULL,
	end_time TIMESTAMP NOT NULL,
	version TEXT NOT NULL
);